### ISSUE TITLE
Unable to approve getf request.

### ISSUE THREAD

**Issue by reubenct** [samvram/Jaggery#3]
![jag_bug1](https://user-images.githubusercontent.com/23528484/38381307-060ea70c-3924-11e8-930c-5377990ab45c.PNG)

Steps to re-create:
1) Start API following provided guidelines.
2) Request 'getf' from another machine 
3) Pressed 'Y' followed by 'Enter' **twice**.

**Comment by ankit98verma** [comment]
The bug has been fixed and a new version has been released.
