### ISSUE TITLE
Display alias for getf request.

### ISSUE THREAD

**Issue by reubenct** [samvram/Jaggery#7]
Currently the interface shows the IP address of another client trying to request a file from the user. 
![jag_bug5](https://user-images.githubusercontent.com/23528484/38463538-f8e9fae2-3b1a-11e8-92fc-5dd1a9192a9a.PNG)
It would be easier to identify the other person if 'alias name' is displayed instead of IP.

**Comment by ankit98verma** [comment]
Solved!
